### ISSUE TITLE
Image broken when deploy the page

### ISSUE THREAD

**Issue by JeongYunLee** [narasimhajupally/tailwind-nuxtjs-starter-blog#1]
Hi, thank you for sharing a nice template.
BTW, I have a problem about setting image path and I want to ask you something.
When I deploy the page, the images got broken on 'author.vue' and 'card.vue'.

I wrote the path on 'default.md' like this:
```
---
name: 
avatar: images/img.jpeg
occupation: 
nationality: 
email:
twitter: 
linkedin:
github: 
---
```

and I wrote the path on 'projectdata.json' like this:
```
[
  {
    "title": "",
    "description": "",
    "imgSrc": "images/img.png",
    "href": ""
  },
]
```

When I deploy the page, the path changed like this: src="/_ipx/s_1440x1440/images/img.jpeg".
I'm using Netlify. 

Please help me if you know the solution! thank you

**Comment by JeongYunLee** [comment]
I just solved the problem!!

Someone(look this issue: https://github.com/nuxt/image/issues/689) said it's a bug on Netlify, and changed build command 'nuxt build' into 'nuxt generate' and it works!!

**Comment by narasimhajupally** [comment]
changed from `nuxt build` into `nuxt build` ? typo ?

**Comment by JeongYunLee** [comment]
<img width="1459" alt="image" src="https://github.com/narasimhajupally/tailwind-nuxtjs-starter-blog/assets/68316386/aef5ad40-1142-4d13-9a04-9cf23e8f18d0">

yes, like this.

**Comment by narasimhajupally** [comment]
I think you mean you changed from `nuxt build` to `nuxt generate`

**Comment by JeongYunLee** [comment]
oops, that was a typo, sorry
